use crate::AdministrativeArea;

#[rustfmt::skip]
pub const ADMINISTRATIVE_AREAS: &[AdministrativeArea] = &[
    AdministrativeArea { code: "JP-01", name_ja: "北海道", name_en: "Hokkaido" },
    AdministrativeArea { code: "JP-02", name_ja: "青森県", name_en: "Aomori" },
    AdministrativeArea { code: "JP-03", name_ja: "岩手県", name_en: "Iwate" },
    AdministrativeArea { code: "JP-04", name_ja: "宮城県", name_en: "Miyagi" },
    AdministrativeArea { code: "JP-05", name_ja: "秋田県", name_en: "Akita" },
    AdministrativeArea { code: "JP-06", name_ja: "山形県", name_en: "Yamagata" },
    AdministrativeArea { code: "JP-07", name_ja: "福島県", name_en: "Fukushima" },
    AdministrativeArea { code: "JP-08", name_ja: "茨城県", name_en: "Ibaraki" },
    AdministrativeArea { code: "JP-09", name_ja: "栃木県", name_en: "Tochigi" },
    AdministrativeArea { code: "JP-10", name_ja: "群馬県", name_en: "Gunma" },
    AdministrativeArea { code: "JP-11", name_ja: "埼玉県", name_en: "Saitama" },
    AdministrativeArea { code: "JP-12", name_ja: "千葉県", name_en: "Chiba" },
    AdministrativeArea { code: "JP-13", name_ja: "東京都", name_en: "Tokyo" },
    AdministrativeArea { code: "JP-14", name_ja: "神奈川県", name_en: "Kanagawa" },
    AdministrativeArea { code: "JP-15", name_ja: "新潟県", name_en: "Niigata" },
    AdministrativeArea { code: "JP-16", name_ja: "富山県", name_en: "Toyama" },
    AdministrativeArea { code: "JP-17", name_ja: "石川県", name_en: "Ishikawa" },
    AdministrativeArea { code: "JP-18", name_ja: "福井県", name_en: "Fukui" },
    AdministrativeArea { code: "JP-19", name_ja: "山梨県", name_en: "Yamanashi" },
    AdministrativeArea { code: "JP-20", name_ja: "長野県", name_en: "Nagano" },
    AdministrativeArea { code: "JP-21", name_ja: "岐阜県", name_en: "Gifu" },
    AdministrativeArea { code: "JP-22", name_ja: "静岡県", name_en: "Shizuoka" },
    AdministrativeArea { code: "JP-23", name_ja: "愛知県", name_en: "Aichi" },
    AdministrativeArea { code: "JP-24", name_ja: "三重県", name_en: "Mie" },
    AdministrativeArea { code: "JP-25", name_ja: "滋賀県", name_en: "Shiga" },
    AdministrativeArea { code: "JP-26", name_ja: "京都府", name_en: "Kyoto" },
    AdministrativeArea { code: "JP-27", name_ja: "大阪府", name_en: "Osaka" },
    AdministrativeArea { code: "JP-28", name_ja: "兵庫県", name_en: "Hyogo" },
    AdministrativeArea { code: "JP-29", name_ja: "奈良県", name_en: "Nara" },
    AdministrativeArea { code: "JP-30", name_ja: "和歌山県", name_en: "Wakayama" },
    AdministrativeArea { code: "JP-31", name_ja: "鳥取県", name_en: "Tottori" },
    AdministrativeArea { code: "JP-32", name_ja: "島根県", name_en: "Shimane" },
    AdministrativeArea { code: "JP-33", name_ja: "岡山県", name_en: "Okayama" },
    AdministrativeArea { code: "JP-34", name_ja: "広島県", name_en: "Hiroshima" },
    AdministrativeArea { code: "JP-35", name_ja: "山口県", name_en: "Yamaguchi" },
    AdministrativeArea { code: "JP-36", name_ja: "徳島県", name_en: "Tokushima" },
    AdministrativeArea { code: "JP-37", name_ja: "香川県", name_en: "Kagawa" },
    AdministrativeArea { code: "JP-38", name_ja: "愛媛県", name_en: "Ehime" },
    AdministrativeArea { code: "JP-39", name_ja: "高知県", name_en: "Kochi" },
    AdministrativeArea { code: "JP-40", name_ja: "福岡県", name_en: "Fukuoka" },
    AdministrativeArea { code: "JP-41", name_ja: "佐賀県", name_en: "Saga" },
    AdministrativeArea { code: "JP-42", name_ja: "長崎県", name_en: "Nagasaki" },
    AdministrativeArea { code: "JP-43", name_ja: "熊本県", name_en: "Kumamoto" },
    AdministrativeArea { code: "JP-44", name_ja: "大分県", name_en: "Oita" },
    AdministrativeArea { code: "JP-45", name_ja: "宮崎県", name_en: "Miyazaki" },
    AdministrativeArea { code: "JP-46", name_ja: "鹿児島県", name_en: "Kagoshima" },
    AdministrativeArea { code: "JP-47", name_ja: "沖縄県", name_en: "Okinawa" },
];
